<?PHP 

// ESTE SENCILLO SCRIPT ES PARA DIRECCIONAR A UN PHP EXISTENTE, USADO PARA EL MENU DE USUARIO CUANDO SE TIENE DESHABILITADO JAVASCRIPT (BOTON IR A)
if(isset($_POST['url'])){
	header("Location: ".$_POST['url']);
}
?>